# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.6

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake.exe

# The command to remove a file.
RM = /usr/bin/cmake.exe -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/Jason/C

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/Jason/C

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake.exe -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake.exe -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/Jason/C/CMakeFiles /home/Jason/C/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/Jason/C/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named gravity

# Build rule for target.
gravity: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gravity
.PHONY : gravity

# fast build rule for target.
gravity/fast:
	$(MAKE) -f CMakeFiles/gravity.dir/build.make CMakeFiles/gravity.dir/build
.PHONY : gravity/fast

src/forces.o: src/forces.cpp.o

.PHONY : src/forces.o

# target to build an object file
src/forces.cpp.o:
	$(MAKE) -f CMakeFiles/gravity.dir/build.make CMakeFiles/gravity.dir/src/forces.cpp.o
.PHONY : src/forces.cpp.o

src/forces.i: src/forces.cpp.i

.PHONY : src/forces.i

# target to preprocess a source file
src/forces.cpp.i:
	$(MAKE) -f CMakeFiles/gravity.dir/build.make CMakeFiles/gravity.dir/src/forces.cpp.i
.PHONY : src/forces.cpp.i

src/forces.s: src/forces.cpp.s

.PHONY : src/forces.s

# target to generate assembly for a file
src/forces.cpp.s:
	$(MAKE) -f CMakeFiles/gravity.dir/build.make CMakeFiles/gravity.dir/src/forces.cpp.s
.PHONY : src/forces.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/gravity.dir/build.make CMakeFiles/gravity.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/gravity.dir/build.make CMakeFiles/gravity.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/gravity.dir/build.make CMakeFiles/gravity.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/particle.o: src/particle.cpp.o

.PHONY : src/particle.o

# target to build an object file
src/particle.cpp.o:
	$(MAKE) -f CMakeFiles/gravity.dir/build.make CMakeFiles/gravity.dir/src/particle.cpp.o
.PHONY : src/particle.cpp.o

src/particle.i: src/particle.cpp.i

.PHONY : src/particle.i

# target to preprocess a source file
src/particle.cpp.i:
	$(MAKE) -f CMakeFiles/gravity.dir/build.make CMakeFiles/gravity.dir/src/particle.cpp.i
.PHONY : src/particle.cpp.i

src/particle.s: src/particle.cpp.s

.PHONY : src/particle.s

# target to generate assembly for a file
src/particle.cpp.s:
	$(MAKE) -f CMakeFiles/gravity.dir/build.make CMakeFiles/gravity.dir/src/particle.cpp.s
.PHONY : src/particle.cpp.s

src/simulator.o: src/simulator.cpp.o

.PHONY : src/simulator.o

# target to build an object file
src/simulator.cpp.o:
	$(MAKE) -f CMakeFiles/gravity.dir/build.make CMakeFiles/gravity.dir/src/simulator.cpp.o
.PHONY : src/simulator.cpp.o

src/simulator.i: src/simulator.cpp.i

.PHONY : src/simulator.i

# target to preprocess a source file
src/simulator.cpp.i:
	$(MAKE) -f CMakeFiles/gravity.dir/build.make CMakeFiles/gravity.dir/src/simulator.cpp.i
.PHONY : src/simulator.cpp.i

src/simulator.s: src/simulator.cpp.s

.PHONY : src/simulator.s

# target to generate assembly for a file
src/simulator.cpp.s:
	$(MAKE) -f CMakeFiles/gravity.dir/build.make CMakeFiles/gravity.dir/src/simulator.cpp.s
.PHONY : src/simulator.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... gravity"
	@echo "... rebuild_cache"
	@echo "... src/forces.o"
	@echo "... src/forces.i"
	@echo "... src/forces.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/particle.o"
	@echo "... src/particle.i"
	@echo "... src/particle.s"
	@echo "... src/simulator.o"
	@echo "... src/simulator.i"
	@echo "... src/simulator.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

